name: Deploy

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run build
        env:
          NODE_ENV: production
      - uses: actions/upload-artifact@v3
        with:
          name: deployment-${{ github.sha }}
          path: dist/
